<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PagesRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|min:5|max:249',
            'alias' => 'required|unique:pages,alias',
            'page' => 'required|min:10'
        ];
    }

    public function messages()
    {
         // TODO: Change the autogenerated stub
        return [
            'title.required'=>'Назва сторінки обов\'язкова',
            'title.min'=>'Назва сторінки коротка, не манше 5 символів',
            'title.max'=>'Назва сторінки довга, не більше 249 символів',
            'alias.required'=>'Url сторінки обов\'язковий',
            'alias.unique'=>'Такий url всже існує, має бути унікальним!',
        ];
    }
}
